version: '3.9'

services:
  # Django App
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stude_backend:latest
    ports:
      - "8000:8000"  # Expose port 8000 for the web server
    environment:
      - PYTHONBUFFERED=1
    command: ["python", "stude/manage.py", "runserver"]
    volumes:
      - stude:/app

volumes:
  stude: