# Generated by Django 4.2.2 on 2023-06-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='x_latitude',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='studentstatus',
            old_name='y_latitude',
            new_name='y',
        ),
    ]
