# Generated by Django 4.2.3 on 2023-07-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
        ('student_status', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='landmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landmarks.landmark'),
        ),
    ]
