# Generated by Django 4.2.2 on 2023-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_status', '0002_rename_x_latitude_studentstatus_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
