# Generated by Django 4.2.3 on 2023-09-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_name_alter_subjectinstance_subject'),
        ('student_status', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', to_field='name'),
        ),
    ]
