# Generated by Django 4.2.2 on 2023-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        ('student_status', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstatus',
            name='study_group',
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='study_group',
            field=models.ManyToManyField(blank=True, null=True, through='study_groups.StudyGroupMembership', to='study_groups.studygroup'),
        ),
    ]
