# Generated by Django 4.2.2 on 2023-06-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_status', '0003_studentstatus_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
