# Generated by Django 4.2.2 on 2023-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        ('student_status', '0003_remove_studentstatus_study_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='study_group',
            field=models.ManyToManyField(blank=True, through='study_groups.StudyGroupMembership', to='study_groups.studygroup'),
        ),
    ]
