# Generated by Django 4.2.2 on 2023-06-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0002_alter_customuser_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(default='BSIT', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
