# Generated by Django 4.2.5 on 2023-09-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='active',
        ),
    ]
