# Generated by Django 4.2.5 on 2023-09-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_remove_studygroup_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
