# Generated by Django 4.2.3 on 2023-07-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subjectcourse',
            name='subject',
        ),
    ]
