# Generated by Django 4.2.3 on 2023-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='shortname',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
