# Generated by Django 4.2.3 on 2023-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjectcourse_alter_subject_courses'),
        ('courses', '0003_remove_subjectcourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='SubjectCourse_course', through='subjects.SubjectCourse', to='subjects.subject'),
        ),
        migrations.DeleteModel(
            name='SubjectCourse',
        ),
    ]
