# Generated by Django 4.2.3 on 2023-07-18 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('year_levels', '0002_alter_year_level_name_alter_year_level_shortname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_course_name_alter_course_shortname'),
        ('semesters', '0002_alter_semester_name_alter_semester_shortname'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', to_field='name'),
        ),
        migrations.AlterField(
            model_name='subjectcourse',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', to_field='name'),
        ),
        migrations.AlterField(
            model_name='subjectsemester',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesters.semester', to_field='name'),
        ),
        migrations.AlterField(
            model_name='subjectsemester',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', to_field='name'),
        ),
        migrations.AlterField(
            model_name='subjectyearlevel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', to_field='name'),
        ),
        migrations.AlterField(
            model_name='subjectyearlevel',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='year_levels.year_level', to_field='name'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectcourse',
            unique_together={('subject', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectsemester',
            unique_together={('subject', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectyearlevel',
            unique_together={('subject', 'year_level')},
        ),
    ]
