# Generated by Django 4.2.3 on 2023-07-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('year_levels', '0001_initial'),
        ('semesters', '0001_initial'),
        ('subjects', '0002_alter_subject_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'course', 'year_level', 'semester')},
        ),
    ]
