# Generated by Django 4.2.3 on 2023-07-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_semester_remove_subject_year_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='courses',
            new_name='course',
        ),
    ]
