# Generated by Django 4.2.3 on 2023-07-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subjectcode_remove_subject_code_subject_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='code',
            new_name='codes',
        ),
    ]
