# Generated by Django 4.2.3 on 2023-07-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_courses_subject_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='courses',
        ),
    ]
