# Generated by Django 4.2.3 on 2023-07-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_rename_course_subject_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='semester',
            new_name='semesters',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='year_level',
            new_name='year_levels',
        ),
    ]
